services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      - redis

  worker:
    build: ./worker
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
